version: '3'
services:
  data_base:
    image: mysql
    container_name: rest_api_db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports: 
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
      # MYSQL_DATABASE: PHPRESTAPI
      MYSQL_USER: vishva
      MYSQL_PASSWORD: admin@123
      MYSQL_ROOT_HOST: '%'
    networks:
      - web
  rest_api:
    container_name: rest_api_website
    build:
      context: ./
    ports:
      - 8001:80
    volumes: 
      - ./src:/var/www/html/
    depends_on:
      - data_base
    networks:
      - web
  # phpmyadmin
  data_base_access:
    depends_on:
      - data_base
    container_name: DB_Access
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    links: 
      - data_base:data_base
    environment:
      PMA_HOST: rest_api_db
      PMA_PORT: 3306
    networks:
      - web
networks:
   web: