version: '3'
services:
  mysqlVishva:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports: 
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vany
      MYSQL_USER: vishva
      MYSQL_PASSWORD: admin@123
      MYSQL_ROOT_HOST: '%'
    networks:
      - web
  website:
    container_name: php72
    build:
      context: ./
    ports:
      - 8001:80
    depends_on:
      - mysqlVishva
    networks:
      - web
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysqlVishva
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    links: 
      - mysqlVishva:mysqlVishva
    environment:
      PMA_HOST: vishva
      PMA_PORT: 3306
    networks:
      - web
networks:
   web: